import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Table from '../components/Table'
import { useRouter } from 'next/router'

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Contrary Portfolio Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="max-w-7xl space-y-8 sm:space-y-5">
          <div className="flex items-center justify-between">
            <h2 className="text-3xl font-bold text-gray-900">
              Contrary Portfolio
            </h2>
            <button
              onClick={() => router.push('/newInvestment')}
              className="ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700"
            >
              Add Investment
            </button>
          </div>

          <Table />
        </div>
      </main>
    </>
  )
}
