import InvestmentForm from '../components/InvestmentForm'
import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function NewInvestment() {
  return (
    <>
      <Head>
        <title>New Investment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="max-w-7xl space-y-8 divide-y divide-gray-200 sm:space-y-5">
          <InvestmentForm />
        </div>
      </main>
    </>
  )
}
